### Programación de la Información
# Examen de Medio Término

Lee con detenmimiento y contesta lo que se te solicita. Antes de finalizar, sube tu archivo en formato .ipynb al espacio correspondiente en Brightspace.

Cada ejercicio tiene el mismo peso.

¡Mucho éxito, y que la suerte esté siempre de su lado!

In [2]:
import pandas as pd
import numpy as np

Corre la siguiente celda. Vas a crear un _diccionario_ de Python, que contiene información sobre algunos precios mensuales de las acciones de Facebook. 

Estos fueron obtenidos del siguiente [proyecto de Kaggle](https://www.kaggle.com/kalilurrahman/facebook-stock-data-live-and-latest), y esta, a su vez, de Yahoo Finances.

Una vez leido, realiza las acciones siguientes:

In [1]:
fb_stock = {'Close': [27.7199993134,
  20.8799991608,
  21.9899997711,
  21.2099990845,
  29.7299995422,
  27.7800006866,
  25.5300006866,
  27.4300003052,
  24.8099994659,
  37.4900016785,
  50.4199981689,
  49.75,
  62.6199989319,
  61.1500015259,
  68.0599975586,
  72.3600006104,
  76.5500030518,
  75.0999984741,
  81.6699981689,
  78.9899978638,
  80.2900009155,
  86.9100036621,
  87.2300033569,
  90.9499969482,
  107.1200027466,
  115.0899963379,
  109.8199996948,
  116.0599975586,
  118.7799987793,
  114.1900024414,
  124.3099975586,
  126.1699981689,
  129.5,
  115.0999984741,
  133.2299957275,
  137.4199981689,
  152.4600067139,
  151.5299987793,
  169.8600006104,
  172.0200042725,
  182.6600036621,
  175.1000061035,
  193.0899963379,
  175.9400024414,
  173.8600006104,
  193.9900054932,
  171.6499938965,
  162.4400024414,
  151.75,
  165.7100067139,
  162.2799987793,
  168.6999969482,
  193.0299987793,
  193.0,
  192.7299957275,
  175.8099975586,
  193.6199951172,
  159.6000061035,
  202.2700042725,
  231.9100036621,
  237.5500030518,
  295.4400024414,
  266.6300048828,
  286.549987793,
  262.0100097656,
  264.9100036621,
  298.6600036621,
  329.1300048828,
  354.3900146484,
  382.049987793,
  343.0100097656],
 'Date': ['2012-06-01',
  '2012-08-01',
  '2012-10-01',
  '2012-11-01',
  '2013-02-01',
  '2013-03-01',
  '2013-04-01',
  '2013-05-01',
  '2013-07-01',
  '2013-08-01',
  '2013-10-01',
  '2013-11-01',
  '2014-04-01',
  '2014-05-01',
  '2014-07-01',
  '2014-08-01',
  '2014-10-01',
  '2014-12-01',
  '2015-04-01',
  '2015-05-01',
  '2015-06-01',
  '2015-07-01',
  '2015-09-01',
  '2015-10-01',
  '2015-12-01',
  '2016-02-01',
  '2016-03-01',
  '2016-04-01',
  '2016-06-01',
  '2016-07-01',
  '2016-08-01',
  '2016-09-01',
  '2016-11-01',
  '2016-12-01',
  '2017-02-01',
  '2017-03-01',
  '2017-05-01',
  '2017-06-01',
  '2017-08-01',
  '2017-09-01',
  '2017-11-01',
  '2017-12-01',
  '2018-02-01',
  '2018-03-01',
  '2018-05-01',
  '2018-06-01',
  '2018-08-01',
  '2018-10-01',
  '2018-11-01',
  '2019-02-01',
  '2019-03-01',
  '2019-04-01',
  '2019-05-01',
  '2019-07-01',
  '2019-08-01',
  '2019-10-01',
  '2019-11-01',
  '2020-04-01',
  '2020-05-01',
  '2020-06-01',
  '2020-07-01',
  '2020-09-01',
  '2020-10-01',
  '2020-12-01',
  '2021-02-01',
  '2021-03-01',
  '2021-04-01',
  '2021-06-01',
  '2021-07-01',
  '2021-09-01',
  '2021-10-01'],
 'High': [29.1499996185,
  21.5799999237,
  22.5900001526,
  21.4400005341,
  31.0200004578,
  28.1200008392,
  25.8899993896,
  27.9200000763,
  25.0599994659,
  38.2900009155,
  51.0299987793,
  52.0900001526,
  62.6599998474,
  62.2799987793,
  68.4400024414,
  73.2200012207,
  78.8199996948,
  77.3099975586,
  82.7200012207,
  79.7600021362,
  80.3799972534,
  87.9499969482,
  89.3899993896,
  90.9499969482,
  107.1500015259,
  115.7200012207,
  109.8199996948,
  116.1699981689,
  119.0800018311,
  115.1299972534,
  124.5800018311,
  126.6299972534,
  131.9400024414,
  118.4499969482,
  133.4900054932,
  137.4799957275,
  152.5700073242,
  152.2899932861,
  170.4700012207,
  172.9199981689,
  182.8999938965,
  177.4799957275,
  195.3200073242,
  180.1199951172,
  174.0200042725,
  194.5500030518,
  175.0800018311,
  165.8800048828,
  152.75,
  169.1000061035,
  163.1300048828,
  168.8999938965,
  196.1799926758,
  195.2799987793,
  198.4700012207,
  179.8399963379,
  194.1100006104,
  164.1499938965,
  207.2799987793,
  232.4400024414,
  239.0,
  301.4899902344,
  268.3299865723,
  289.299987793,
  264.1700134277,
  266.6499938965,
  302.3999938965,
  331.4200134277,
  354.6700134277,
  384.3299865723,
  345.0100097656],
 'Low': [27.3899993896,
  20.8400001526,
  21.7299995422,
  21.0100002289,
  29.6299991608,
  26.8099994659,
  25.2800006866,
  27.3099994659,
  24.6200008392,
  36.9199981689,
  49.4500007629,
  49.7200012207,
  60.2400016785,
  60.2099990845,
  67.3899993896,
  71.5500030518,
  75.9000015259,
  74.8000030518,
  80.8700027466,
  78.1100006104,
  78.6600036621,
  86.4899978638,
  86.5,
  88.3600006104,
  104.5,
  112.0100021362,
  107.5999984741,
  113.3499984741,
  117.8199996948,
  113.8099975586,
  122.8600006104,
  125.5999984741,
  128.6499938965,
  114.0,
  130.6799926758,
  136.3000030518,
  151.4199981689,
  150.3000030518,
  169.0500030518,
  171.3099975586,
  180.5700073242,
  172.3399963379,
  187.8899993896,
  174.4100036621,
  170.2299957275,
  192.0700073242,
  170.8999938965,
  161.2599945068,
  149.3500061035,
  165.6600036621,
  161.6900024414,
  167.2799987793,
  193.0099945068,
  191.9299926758,
  190.8800048828,
  174.8800048828,
  189.9100036621,
  158.0399932861,
  199.0500030518,
  223.5,
  227.5599975586,
  292.7099914551,
  264.799987793,
  278.9599914551,
  254.9100036621,
  257.8999938965,
  296.6000061035,
  326.6400146484,
  346.5,
  378.8099975586,
  338.6400146484],
 'Open': [28.8899993896,
  21.5,
  22.0799999237,
  21.0799999237,
  31.0100002289,
  27.0499992371,
  25.6299991608,
  27.8500003815,
  24.9699993134,
  37.2999992371,
  49.9700012207,
  50.8499984741,
  60.4599990845,
  60.4300003052,
  67.5800018311,
  72.2200012207,
  78.7799987793,
  77.2600021362,
  82.5,
  79.2399978638,
  79.3000030518,
  86.7699966431,
  86.8499984741,
  90.0500030518,
  104.8300018311,
  112.2699966431,
  107.8300018311,
  113.75,
  118.5,
  114.1999969482,
  123.8499984741,
  126.3799972534,
  131.4100036621,
  118.3799972534,
  132.25,
  136.4700012207,
  151.7400054932,
  151.75,
  169.8200073242,
  172.3999938965,
  182.3600006104,
  176.0299987793,
  188.2200012207,
  179.0099945068,
  172.0,
  193.0700073242,
  173.9299926758,
  163.0299987793,
  151.5200042725,
  165.8399963379,
  162.6000061035,
  167.8300018311,
  194.7799987793,
  195.2100067139,
  194.1699981689,
  179.1499938965,
  192.8500061035,
  161.6199951172,
  201.6000061035,
  224.5899963379,
  228.5,
  294.7099914551,
  265.3500061035,
  279.1600036621,
  259.5199890137,
  260.8200073242,
  298.3999938965,
  330.1499938965,
  346.8200073242,
  379.5899963379,
  341.6099853516],
 'Stock Splits': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'Volume': [41855500,
  44604400,
  51262700,
  37713900,
  85856700,
  54064800,
  22249300,
  64567600,
  20582200,
  106066500,
  98114000,
  95033000,
  59291000,
  82429000,
  33243000,
  43535000,
  55090000,
  31789900,
  22058200,
  24136400,
  18119000,
  25260000,
  36097400,
  29283700,
  22781900,
  46132700,
  26817300,
  24760500,
  15029500,
  14980000,
  25006900,
  13536100,
  22077800,
  43277000,
  50139800,
  16257000,
  25218300,
  14530600,
  14385000,
  11677600,
  40918300,
  20182500,
  54211300,
  23201600,
  26025900,
  17307200,
  34042100,
  26407700,
  25640800,
  30806500,
  11097800,
  10381500,
  15996600,
  14181800,
  17777000,
  17073000,
  21711800,
  19507600,
  30415600,
  18223800,
  43399700,
  17295900,
  20009800,
  20738900,
  22914300,
  22157300,
  17616000,
  11765900,
  17137000,
  11567200,
  14789507]}

¡Es un diccionario demasiado grande!
Para poder conocerlo mejor:
### 1. Imprime las llaves del diccionario *fb_stocks*.


### 2. Crea una lista, llamada _dobleVolumen_. Guarda en ella los valores de df["Volumen"], pero multiplicados por dos.
Tip: nota cómo, si sólo ves df["Volumen"], tienes una lista. ¿Qué tenías que hacer cuando querías hacer cálculos con una lista?

### 3. Programa lo siguiente: "Si el cuarto valor de _dobleVolumen_ es mayor que 70000000, agrega 1234 al final de la lista. Si es igual, imprime la longitud de _dobleVolumen_."

### 4. Convierte _dobleVolumen_ a un arreglo de Numpy. Guardalo con el nombre _arregloVolumen_.

### 5. Calcula la raiz cuadrada de los elementos de _arregloVolumen_

### 6. Convierte fb_stock a un Data Frame de Pandas. Guardalo con el nombre _df_. 
Usa df.head() para verificar tu resultado.

### 7. Libre: ¡Conoce mejor tu tabla! Realiza al menos **dos** cosas que creas que te van ayudar a conocer mejor tus datos.
Si tienes tiempo y pones más de dos, quizá tengas algún punto extra...

### 8. Usa .min() para conocer el valor mínimo de la columna "Volume" de _df_
Tip: `.max()` y `.min()` funcionan muy parecido a `.sum`() o `.mean()`

### 9. Calcula, sin copiar y pegar directamente los valores, la diferencia entre el precio de Cierre("Close") del 2012-11-01 y 2012-10-01. 

Tip: puedes ocupar `.loc` o `.iloc` para seleccionar los valores que necesitas.

La tasa de cambio de una acción es la diferencia entre el precio de cierre y el precio de apertura, dividida entre el precio de apertura. 
### 10. Calcula la tasa de cambio. Guarda el resultado en una columna llamada "Cambio"